name: Generate Snake Animation

# izinkan Action untuk push file ke repo
permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"   # update sekali sehari (UTC). Ganti kalau mau frekuensi lain
  workflow_dispatch:      # memungkinkan run manual dari UI
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake SVG (Platane/snk)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#0ba9b4&color_dots=#161b22,#073e42,#0a6b72,#0ba9b4,#14d9e6

      - name: Publish `dist/` to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
